export interface tile {
  name: string;
  type:
    | 'colored'
    | 'railroad'
    | 'utilities'
    | 'chance'
    | 'community_chest'
    | 'income_tax'
    | 'luxury_tax'
    | 'go'
    | 'jail'
    | 'free_parking'
    | 'go_to_jail'
    | 'visiting_jail';
  attributes: {
    color?: string | null;
    visitingJail?: boolean;
    collectMoney?: { amount: number } | null;
    cost?: number | null;
    rent_amount?: number | null;
    mortgageable?: boolean;
    houseCost?: number | null;
    rent1House?: number | null;
    rent2Houses?: number | null;
    rent3Houses?: number | null;
    rent4Houses?: number | null;
    rentHotel?: number | null;
  };
  location: number;
}

export const tiles: tile[] = [
  {
    name: 'GO',
    type: 'go',
    location: 0,
    attributes: {
      collectMoney: { amount: 200 },
    },
  },
  {
    name: 'Mediterranean Avenue',
    type: 'colored',
    attributes: {
      color: 'brown',
      cost: 60,
      rent_amount: 2,
      mortgageable: true,
      houseCost: 50,
      rent1House: 10,
      rent2Houses: 30,
      rent3Houses: 90,
      rent4Houses: 160,
      rentHotel: 250,
    },
    location: 1,
  },
  {
    name: 'Community Chest',
    type: 'community_chest',
    attributes: {},
    location: 2,
  },
  {
    name: 'Baltic Avenue',
    type: 'colored',
    attributes: {
      color: 'brown',
      cost: 60,
      rent_amount: 4,
      mortgageable: true,
      houseCost: 50,
      rent1House: 20,
      rent2Houses: 60,
      rent3Houses: 180,
      rent4Houses: 320,
      rentHotel: 450,
    },
    location: 3,
  },
  {
    name: 'Income Tax',
    type: 'income_tax',
    attributes: {},
    location: 4,
  },
  {
    name: 'Reading Railroad',
    type: 'railroad',
    attributes: {
      mortgageable: true,
      cost: 200,
      rent_amount: 25,
    },
    location: 5,
  },
  {
    name: 'Oriental Avenue',
    type: 'colored',
    attributes: {
      color: 'light_blue',
      cost: 100,
      rent_amount: 6,
      mortgageable: true,
      houseCost: 50,
      rent1House: 30,
      rent2Houses: 90,
      rent3Houses: 270,
      rent4Houses: 400,
      rentHotel: 550,
    },
    location: 6,
  },
  {
    name: 'Chance',
    type: 'chance',
    attributes: {},
    location: 7,
  },
  {
    name: 'Vermont Avenue',
    type: 'colored',
    attributes: {
      color: 'light_blue',
      cost: 100,
      rent_amount: 6,
      mortgageable: true,
      houseCost: 50,
      rent1House: 30,
      rent2Houses: 90,
      rent3Houses: 270,
      rent4Houses: 400,
      rentHotel: 550,
    },
    location: 8,
  },
  {
    name: 'Connecticut Avenue',
    type: 'colored',
    attributes: {
      color: 'light_blue',
      cost: 120,
      rent_amount: 8,
      mortgageable: true,
      houseCost: 50,
      rent1House: 40,
      rent2Houses: 100,
      rent3Houses: 300,
      rent4Houses: 450,
      rentHotel: 600,
    },
    location: 9,
  },
  {
    name: 'Just Visiting',
    type: 'visiting_jail',
    attributes: {
      visitingJail: true,
    },
    location: 10,
  },
  {
    name: 'St. Charles Place',
    type: 'colored',
    attributes: {
      color: 'pink',
      cost: 140,
      rent_amount: 10,
      mortgageable: true,
      houseCost: 100,
      rent1House: 50,
      rent2Houses: 150,
      rent3Houses: 450,
      rent4Houses: 625,
      rentHotel: 750,
    },
    location: 11,
  },
  {
    name: 'Electric Company',
    type: 'utilities',
    attributes: {
      mortgageable: true,
      cost: 150,
      rent_amount: 0,
    },
    location: 12,
  },
  {
    name: 'States Avenue',
    type: 'colored',
    attributes: {
      color: 'pink',
      cost: 140,
      rent_amount: 10,
      mortgageable: true,
      houseCost: 100,
      rent1House: 50,
      rent2Houses: 150,
      rent3Houses: 450,
      rent4Houses: 625,
      rentHotel: 750,
    },
    location: 13,
  },
  {
    name: 'Virginia Avenue',
    type: 'colored',
    attributes: {
      color: 'pink',
      cost: 160,
      rent_amount: 12,
      mortgageable: true,
      houseCost: 100,
      rent1House: 60,
      rent2Houses: 180,
      rent3Houses: 500,
      rent4Houses: 700,
      rentHotel: 900,
    },
    location: 14,
  },
  {
    name: 'Pennsylvania Railroad',
    type: 'railroad',
    attributes: {
      mortgageable: true,
      cost: 200,
      rent_amount: 25,
    },
    location: 15,
  },
  {
    name: 'St. James Place',
    type: 'colored',
    attributes: {
      color: 'orange',
      cost: 180,
      rent_amount: 14,
      mortgageable: true,
      houseCost: 100,
      rent1House: 70,
      rent2Houses: 200,
      rent3Houses: 550,
      rent4Houses: 750,
      rentHotel: 950,
    },
    location: 16,
  },
  {
    name: 'Community Chest',
    type: 'community_chest',
    attributes: {},
    location: 17,
  },
  {
    name: 'Tennessee Avenue',
    type: 'colored',
    attributes: {
      color: 'orange',
      cost: 180,
      rent_amount: 14,
      mortgageable: true,
      houseCost: 100,
      rent1House: 70,
      rent2Houses: 200,
      rent3Houses: 550,
      rent4Houses: 750,
      rentHotel: 950,
    },
    location: 18,
  },
  {
    name: 'New York Avenue',
    type: 'colored',
    attributes: {
      color: 'orange',
      cost: 200,
      rent_amount: 16,
      mortgageable: true,
      houseCost: 100,
      rent1House: 80,
      rent2Houses: 220,
      rent3Houses: 600,
      rent4Houses: 800,
      rentHotel: 1000,
    },
    location: 19,
  },
  {
    name: 'Free Parking',
    type: 'free_parking',
    attributes: {},
    location: 20,
  },
  {
    name: 'Kentucky Avenue',
    type: 'colored',
    attributes: {
      color: 'red',
      cost: 220,
      rent_amount: 18,
      mortgageable: true,
      houseCost: 150,
      rent1House: 90,
      rent2Houses: 250,
      rent3Houses: 700,
      rent4Houses: 875,
      rentHotel: 1050,
    },
    location: 21,
  },
  {
    name: 'Chance',
    type: 'chance',
    attributes: {},
    location: 22,
  },
  {
    name: 'Indiana Avenue',
    type: 'colored',
    attributes: {
      color: 'red',
      cost: 220,
      rent_amount: 18,
      mortgageable: true,
      houseCost: 150,
      rent1House: 90,
      rent2Houses: 250,
      rent3Houses: 700,
      rent4Houses: 875,
      rentHotel: 1050,
    },
    location: 23,
  },
  {
    name: 'Illinois Avenue',
    type: 'colored',
    attributes: {
      color: 'red',
      cost: 240,
      rent_amount: 20,
      mortgageable: true,
      houseCost: 150,
      rent1House: 100,
      rent2Houses: 300,
      rent3Houses: 750,
      rent4Houses: 925,
      rentHotel: 1100,
    },
    location: 24,
  },
  {
    name: 'B&O Railroad',
    type: 'railroad',
    attributes: {
      mortgageable: true,
      cost: 200,
      rent_amount: 25,
    },
    location: 25,
  },
  {
    name: 'Atlantic Avenue',
    type: 'colored',
    attributes: {
      color: 'yellow',
      cost: 260,
      rent_amount: 22,
      mortgageable: true,
      houseCost: 150,
      rent1House: 110,
      rent2Houses: 330,
      rent3Houses: 800,
      rent4Houses: 975,
      rentHotel: 1150,
    },
    location: 26,
  },
  {
    name: 'Ventnor Avenue',
    type: 'colored',
    attributes: {
      color: 'yellow',
      cost: 260,
      rent_amount: 22,
      mortgageable: true,
      houseCost: 150,
      rent1House: 110,
      rent2Houses: 330,
      rent3Houses: 800,
      rent4Houses: 975,
      rentHotel: 1150,
    },
    location: 27,
  },
  {
    name: 'Water Works',
    type: 'utilities',
    attributes: {
      mortgageable: true,
      cost: 150,
      rent_amount: 0,
    },
    location: 28,
  },
  {
    name: 'Marvin Gardens',
    type: 'colored',
    attributes: {
      color: 'yellow',
      cost: 280,
      rent_amount: 24,
      mortgageable: true,
      houseCost: 150,
      rent1House: 120,
      rent2Houses: 360,
      rent3Houses: 850,
      rent4Houses: 1025,
      rentHotel: 1200,
    },
    location: 29,
  },
  {
    name: 'Go To Jail',
    type: 'go_to_jail',
    attributes: {},
    location: 30,
  },
  {
    name: 'Pacific Avenue',
    type: 'colored',
    attributes: {
      color: 'green',
      cost: 300,
      rent_amount: 26,
      mortgageable: true,
      houseCost: 200,
      rent1House: 130,
      rent2Houses: 390,
      rent3Houses: 900,
      rent4Houses: 1100,
      rentHotel: 1275,
    },
    location: 31,
  },
  {
    name: 'North Carolina Avenue',
    type: 'colored',
    attributes: {
      color: 'green',
      cost: 300,
      rent_amount: 26,
      mortgageable: true,
      houseCost: 200,
      rent1House: 130,
      rent2Houses: 390,
      rent3Houses: 900,
      rent4Houses: 1100,
      rentHotel: 1275,
    },
    location: 32,
  },
  {
    name: 'Community Chest',
    type: 'community_chest',
    attributes: {},
    location: 33,
  },
  {
    name: 'Pennsylvania Avenue',
    type: 'colored',
    attributes: {
      color: 'green',
      cost: 320,
      rent_amount: 28,
      mortgageable: true,
      houseCost: 200,
      rent1House: 150,
      rent2Houses: 450,
      rent3Houses: 1000,
      rent4Houses: 1200,
      rentHotel: 1400,
    },
    location: 34,
  },
  {
    name: 'Short Line',
    type: 'railroad',
    attributes: {
      mortgageable: true,
      cost: 200,
      rent_amount: 25,
    },
    location: 35,
  },
  {
    name: 'Chance',
    type: 'chance',
    attributes: {},
    location: 36,
  },
  {
    name: 'Park Place',
    type: 'colored',
    attributes: {
      color: 'dark_blue',
      cost: 350,
      rent_amount: 35,
      mortgageable: true,
      houseCost: 200,
      rent1House: 175,
      rent2Houses: 500,
      rent3Houses: 1100,
      rent4Houses: 1300,
      rentHotel: 1500,
    },
    location: 37,
  },
  {
    name: 'Luxury Tax',
    type: 'luxury_tax',
    attributes: {},
    location: 38,
  },
  {
    name: 'Boardwalk',
    type: 'colored',
    attributes: {
      color: 'dark_blue',
      cost: 400,
      rent_amount: 50,
      mortgageable: true,
      houseCost: 200,
      rent1House: 200,
      rent2Houses: 600,
      rent3Houses: 1400,
      rent4Houses: 1700,
      rentHotel: 2000,
    },
    location: 39,
  },
];
